import Head from 'next/head'
 
 
 
import React, {useState } from 'react';
import TreeContainer from '@/components/TreeContainer';
import Input from '@/components/Input';

 

function Home (){
  const [values, setValues] = useState<string[]>([]);

  const changeHandler = (values:string[]) =>{
    setValues(values)
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
       <Input onChange={changeHandler}/>
        <div className="w-full flex-wrap flex items-start justify-center h-screen mt-10">
          <TreeContainer values={values} />
        </div>
      </section>
    </>
  )
}

export default Home;